# Generated by Django 5.0.6 on 2024-06-02 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sample_swagger", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Item",
            new_name="ItemModel",
        ),
    ]
